--
-- PostgreSQL database dump
--

\restrict 3XhUOB0vpqz1VuaAbypSrwfMuymbNe2d8fUJypD2ikVTQAgFtSkGNLUnggQiPKY

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-01-09 21:39:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: audits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audits (
    id bigint NOT NULL,
    date_audit date,
    date_cloture timestamp(6) without time zone,
    date_creation timestamp(6) without time zone NOT NULL,
    date_debut timestamp(6) without time zone,
    date_modification timestamp(6) without time zone,
    date_validation timestamp(6) without time zone,
    duree_estimee integer,
    duree_reelle integer,
    nb_conformes integer,
    nb_non_applicables integer,
    nb_non_conformes integer,
    nb_partiels integer,
    observation_generale text,
    statut character varying(30) NOT NULL,
    taux_conformite numeric(5,2),
    taux_conformite_pondere numeric(5,2),
    type character varying(30) NOT NULL,
    audit_initial_id bigint,
    auditeur_id bigint NOT NULL,
    etablissement_id bigint NOT NULL,
    validateur_id bigint,
    CONSTRAINT audits_statut_check CHECK (((statut)::text = ANY ((ARRAY['PLANIFIE'::character varying, 'EN_COURS'::character varying, 'TERMINE'::character varying, 'VALIDE'::character varying, 'REJETE'::character varying, 'ARCHIVE'::character varying])::text[]))),
    CONSTRAINT audits_type_check CHECK (((type)::text = ANY ((ARRAY['INITIAL'::character varying, 'PERIODIQUE'::character varying, 'CONTRE_VISITE'::character varying, 'EXCEPTIONNEL'::character varying])::text[])))
);


ALTER TABLE public.audits OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: audits_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16406)
-- Name: commentaires; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.commentaires (
    id bigint NOT NULL,
    contenu text NOT NULL,
    date_creation timestamp(6) without time zone NOT NULL,
    date_modification timestamp(6) without time zone,
    audit_id bigint NOT NULL,
    auteur_id bigint NOT NULL,
    parent_id bigint
);


ALTER TABLE public.commentaires OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16405)
-- Name: commentaires_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.commentaires ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commentaires_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16419)
-- Name: criteres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.criteres (
    id bigint NOT NULL,
    categorie character varying(30) NOT NULL,
    code character varying(50) NOT NULL,
    criticite character varying(20) NOT NULL,
    description text,
    libelle character varying(500) NOT NULL,
    obligatoire boolean NOT NULL,
    ponderation integer NOT NULL,
    preuves_requises text,
    reference_texte_loi character varying(200),
    norme_id bigint NOT NULL,
    section_id bigint,
    CONSTRAINT criteres_categorie_check CHECK (((categorie)::text = ANY ((ARRAY['ACCESSIBILITE'::character varying, 'ISOLEMENT_TIERS'::character varying, 'RESISTANCE_FEU_STRUCTURES'::character varying, 'FACADE'::character varying, 'DISTRIBUTION_INTERIEURE'::character varying, 'LOCAUX_RISQUE'::character varying, 'CONDUITS_GAINES'::character varying, 'DEGAGEMENTS'::character varying, 'AMENAGEMENTS_INTERIEURS'::character varying, 'DESENFUMAGE'::character varying, 'CHAUFFAGE'::character varying, 'INSTALLATIONS_ELECTRIQUES'::character varying, 'ECLAIRAGE_SECURITE'::character varying, 'MOYENS_SECOURS'::character varying, 'DETECTION_ALARME'::character varying, 'SYSTEME_EXTINCTION_AUTOMATIQUE'::character varying, 'EXTINCTEURS'::character varying, 'ROBINETS_INCENDIE_ARMEE'::character varying, 'COLONNES_SECHES'::character varying, 'COLONNES_HUMIDES'::character varying, 'CIRCULATION_HORIZONTALE'::character varying, 'ESCALIERS'::character varying, 'ISSUES_SORTIES'::character varying, 'ASCENSEURS'::character varying, 'COMPARTIMENTAGE'::character varying, 'CLOISONNEMENT'::character varying, 'COUVERTURES'::character varying, 'PLANCHERS'::character varying, 'PLAFONDS_SUSPENDUS'::character varying, 'REVETEMENTS_MURAUX'::character varying, 'REVETEMENTS_SOL'::character varying, 'REACTION_FEU_MATERIAUX'::character varying, 'VENTILATION'::character varying, 'LOCAUX_TECHNIQUES'::character varying, 'STOCKAGE_PRODUITS_DANGEREUX'::character varying, 'FORMATION_PERSONNEL'::character varying, 'EXERCICES_EVACUATION'::character varying, 'CONSIGNES_SECURITE'::character varying, 'EXTINCTEURS_PORTATIFS'::character varying, 'PLANS_EVACUATION'::character varying, 'REGISTRE_SECURITE'::character varying, 'VERIFICATION_PERIODIQUE'::character varying, 'MAINTENANCE_EQUIPEMENTS'::character varying, 'CONTROLES_REGLEMENTAIRES'::character varying, 'PARCS_STATIONNEMENT'::character varying, 'AUTRE'::character varying])::text[]))),
    CONSTRAINT criteres_criticite_check CHECK (((criticite)::text = ANY ((ARRAY['CRITIQUE'::character varying, 'IMPORTANTE'::character varying, 'NORMALE'::character varying, 'FAIBLE'::character varying])::text[]))),
    CONSTRAINT criteres_ponderation_check CHECK (((ponderation <= 5) AND (ponderation >= 1)))
);


ALTER TABLE public.criteres OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16418)
-- Name: criteres_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.criteres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.criteres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16438)
-- Name: etablissements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.etablissements (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    adresse character varying(255),
    capacite_accueil integer,
    code_postal character varying(20),
    date_creation timestamp(6) without time zone NOT NULL,
    date_modification timestamp(6) without time zone,
    description text,
    nom character varying(200) NOT NULL,
    nombre_etages integer,
    pays character varying(100),
    responsable_email character varying(100),
    responsable_nom character varying(100),
    responsable_telephone character varying(20),
    surface_totale double precision,
    type character varying(50) NOT NULL,
    ville character varying(100),
    norme_id bigint NOT NULL,
    CONSTRAINT etablissements_type_check CHECK (((type)::text = ANY ((ARRAY['ERP_TYPE_J'::character varying, 'ERP_TYPE_L'::character varying, 'ERP_TYPE_M'::character varying, 'ERP_TYPE_N'::character varying, 'ERP_TYPE_O'::character varying, 'ERP_TYPE_P'::character varying, 'ERP_TYPE_R'::character varying, 'ERP_TYPE_S'::character varying, 'ERP_TYPE_T'::character varying, 'ERP_TYPE_U'::character varying, 'ERP_TYPE_V'::character varying, 'ERP_TYPE_W'::character varying, 'ERP_TYPE_X'::character varying, 'ERP_TYPE_Y'::character varying, 'ERP_TYPE_PA'::character varying, 'ERP_TYPE_CTS'::character varying, 'ERP_TYPE_SG'::character varying, 'ERP_TYPE_OA'::character varying, 'ERP_TYPE_PS'::character varying, 'ERP_TYPE_GA'::character varying, 'ERP_TYPE_EF'::character varying, 'ERP_TYPE_BM'::character varying, 'BH_1ERE_FAMILLE'::character varying, 'BH_2EME_FAMILLE'::character varying, 'BH_3EME_FAMILLE'::character varying, 'BH_4EME_FAMILLE'::character varying, 'IGH_GHA'::character varying, 'IGH_GHO'::character varying, 'IGH_GHR'::character varying, 'IGH_GHS'::character varying, 'IGH_GHU'::character varying, 'IGH_GHW'::character varying, 'IGH_GHZ'::character varying, 'IGH_GHTC'::character varying, 'IGH_ITGH'::character varying, 'ERT'::character varying, 'AUTRE'::character varying])::text[])))
);


ALTER TABLE public.etablissements OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16437)
-- Name: etablissements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.etablissements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.etablissements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16453)
-- Name: evaluations_criteres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluations_criteres (
    id bigint NOT NULL,
    action_corrective text,
    corrigee boolean NOT NULL,
    cout_estime double precision,
    date_correction_signalee timestamp(6) without time zone,
    date_echeance date,
    date_evaluation timestamp(6) without time zone,
    date_modification timestamp(6) without time zone,
    observation text,
    responsable_action character varying(200),
    statut character varying(30),
    urgence character varying(20),
    audit_id bigint NOT NULL,
    critere_id bigint NOT NULL,
    CONSTRAINT evaluations_criteres_statut_check CHECK (((statut)::text = ANY ((ARRAY['CONFORME'::character varying, 'NON_CONFORME'::character varying, 'PARTIELLEMENT_CONFORME'::character varying, 'NON_APPLICABLE'::character varying, 'NON_EVALUE'::character varying])::text[]))),
    CONSTRAINT evaluations_criteres_urgence_check CHECK (((urgence)::text = ANY ((ARRAY['IMMEDIATE'::character varying, 'COURT_TERME'::character varying, 'MOYEN_TERME'::character varying, 'LONG_TERME'::character varying])::text[])))
);


ALTER TABLE public.evaluations_criteres OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16452)
-- Name: evaluations_criteres_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluations_criteres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluations_criteres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16467)
-- Name: historique_actions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.historique_actions (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    adresseip character varying(45),
    anciens_valeurs text,
    date_action timestamp(6) without time zone NOT NULL,
    description text,
    entite character varying(50) NOT NULL,
    entite_id bigint,
    nouvelles_valeurs text,
    user_agent character varying(500),
    utilisateur_id bigint NOT NULL
);


ALTER TABLE public.historique_actions OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16466)
-- Name: historique_actions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.historique_actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historique_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16479)
-- Name: norme_types_etablissements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.norme_types_etablissements (
    norme_id bigint NOT NULL,
    type_etablissement character varying(255),
    CONSTRAINT norme_types_etablissements_type_etablissement_check CHECK (((type_etablissement)::text = ANY ((ARRAY['ERP_TYPE_J'::character varying, 'ERP_TYPE_L'::character varying, 'ERP_TYPE_M'::character varying, 'ERP_TYPE_N'::character varying, 'ERP_TYPE_O'::character varying, 'ERP_TYPE_P'::character varying, 'ERP_TYPE_R'::character varying, 'ERP_TYPE_S'::character varying, 'ERP_TYPE_T'::character varying, 'ERP_TYPE_U'::character varying, 'ERP_TYPE_V'::character varying, 'ERP_TYPE_W'::character varying, 'ERP_TYPE_X'::character varying, 'ERP_TYPE_Y'::character varying, 'ERP_TYPE_PA'::character varying, 'ERP_TYPE_CTS'::character varying, 'ERP_TYPE_SG'::character varying, 'ERP_TYPE_OA'::character varying, 'ERP_TYPE_PS'::character varying, 'ERP_TYPE_GA'::character varying, 'ERP_TYPE_EF'::character varying, 'ERP_TYPE_BM'::character varying, 'BH_1ERE_FAMILLE'::character varying, 'BH_2EME_FAMILLE'::character varying, 'BH_3EME_FAMILLE'::character varying, 'BH_4EME_FAMILLE'::character varying, 'IGH_GHA'::character varying, 'IGH_GHO'::character varying, 'IGH_GHR'::character varying, 'IGH_GHS'::character varying, 'IGH_GHU'::character varying, 'IGH_GHW'::character varying, 'IGH_GHZ'::character varying, 'IGH_GHTC'::character varying, 'IGH_ITGH'::character varying, 'ERT'::character varying, 'AUTRE'::character varying])::text[])))
);


ALTER TABLE public.norme_types_etablissements OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16485)
-- Name: normes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.normes (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    code character varying(50) NOT NULL,
    date_creation timestamp(6) without time zone NOT NULL,
    date_modification timestamp(6) without time zone,
    date_vigueur date,
    description text,
    nom character varying(200) NOT NULL,
    pays character varying(100),
    version character varying(20)
);


ALTER TABLE public.normes OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16484)
-- Name: normes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.normes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.normes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16498)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    date_creation timestamp(6) without time zone NOT NULL,
    date_lecture timestamp(6) without time zone,
    lien character varying(500),
    lu boolean NOT NULL,
    message text NOT NULL,
    titre character varying(200) NOT NULL,
    type character varying(50) NOT NULL,
    destinataire_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['AUDIT_PLANIFIE'::character varying, 'AUDIT_TERMINE'::character varying, 'VALIDATION_REQUISE'::character varying, 'NON_CONFORMITE_CRITIQUE'::character varying, 'AUDIT_EXPIRE'::character varying, 'COMMENTAIRE_AJOUTE'::character varying, 'MENTION'::character varying, 'RAPPORT_GENERE'::character varying, 'SYSTEME'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16497)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16514)
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    date_creation timestamp(6) without time zone NOT NULL,
    date_expiration timestamp(6) without time zone NOT NULL,
    date_utilisation timestamp(6) without time zone,
    token character varying(255) NOT NULL,
    utilise boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16513)
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16526)
-- Name: photos_etablissement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photos_etablissement (
    id bigint NOT NULL,
    chemin_fichier character varying(500) NOT NULL,
    date_upload timestamp(6) without time zone NOT NULL,
    description character varying(500),
    nom_fichier character varying(255) NOT NULL,
    principale boolean NOT NULL,
    taille_fichier bigint,
    etablissement_id bigint NOT NULL
);


ALTER TABLE public.photos_etablissement OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16525)
-- Name: photos_etablissement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photos_etablissement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photos_etablissement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16540)
-- Name: preuves; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.preuves (
    id bigint NOT NULL,
    chemin_fichier character varying(500) NOT NULL,
    date_upload timestamp(6) without time zone NOT NULL,
    description character varying(500),
    nom_fichier character varying(255) NOT NULL,
    taille_fichier bigint,
    type_fichier character varying(20) NOT NULL,
    evaluation_id bigint NOT NULL,
    CONSTRAINT preuves_type_fichier_check CHECK (((type_fichier)::text = ANY ((ARRAY['IMAGE'::character varying, 'PDF'::character varying, 'WORD'::character varying, 'EXCEL'::character varying, 'VIDEO'::character varying, 'AUTRE'::character varying])::text[])))
);


ALTER TABLE public.preuves OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16539)
-- Name: preuves_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.preuves ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.preuves_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16555)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(20) NOT NULL,
    CONSTRAINT roles_name_check CHECK (((name)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'AUDITOR'::character varying])::text[])))
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16554)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16564)
-- Name: sections; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sections (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    date_creation timestamp(6) without time zone,
    date_modification timestamp(6) without time zone,
    description text,
    ordre integer NOT NULL,
    titre character varying(200) NOT NULL,
    norme_id bigint NOT NULL
);


ALTER TABLE public.sections OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16563)
-- Name: sections_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 16576)
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 16584)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    date_creation timestamp(6) without time zone NOT NULL,
    date_modification timestamp(6) without time zone,
    derniere_connexion timestamp(6) without time zone,
    email character varying(100) NOT NULL,
    nom character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    prenom character varying(50) NOT NULL,
    telephone character varying(20),
    username character varying(50) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 16583)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4942 (class 2606 OID 16404)
-- Name: audits audits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT audits_pkey PRIMARY KEY (id);


--
-- TOC entry 4949 (class 2606 OID 16417)
-- Name: commentaires commentaires_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commentaires
    ADD CONSTRAINT commentaires_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 16436)
-- Name: criteres criteres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.criteres
    ADD CONSTRAINT criteres_pkey PRIMARY KEY (id);


--
-- TOC entry 4959 (class 2606 OID 16451)
-- Name: etablissements etablissements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etablissements
    ADD CONSTRAINT etablissements_pkey PRIMARY KEY (id);


--
-- TOC entry 4964 (class 2606 OID 16465)
-- Name: evaluations_criteres evaluations_criteres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluations_criteres
    ADD CONSTRAINT evaluations_criteres_pkey PRIMARY KEY (id);


--
-- TOC entry 4970 (class 2606 OID 16478)
-- Name: historique_actions historique_actions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historique_actions
    ADD CONSTRAINT historique_actions_pkey PRIMARY KEY (id);


--
-- TOC entry 4978 (class 2606 OID 16496)
-- Name: normes normes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.normes
    ADD CONSTRAINT normes_pkey PRIMARY KEY (id);


--
-- TOC entry 4986 (class 2606 OID 16512)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 4990 (class 2606 OID 16524)
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 4994 (class 2606 OID 16538)
-- Name: photos_etablissement photos_etablissement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_etablissement
    ADD CONSTRAINT photos_etablissement_pkey PRIMARY KEY (id);


--
-- TOC entry 4998 (class 2606 OID 16553)
-- Name: preuves preuves_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preuves
    ADD CONSTRAINT preuves_pkey PRIMARY KEY (id);


--
-- TOC entry 5000 (class 2606 OID 16562)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 5004 (class 2606 OID 16575)
-- Name: sections sections_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (id);


--
-- TOC entry 5006 (class 2606 OID 16638)
-- Name: sections uk38b6of0w5giyqjqpv8dh2hpx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT uk38b6of0w5giyqjqpv8dh2hpx UNIQUE (norme_id, code);


--
-- TOC entry 5012 (class 2606 OID 16642)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4992 (class 2606 OID 16632)
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- TOC entry 4980 (class 2606 OID 16624)
-- Name: normes ukm0k8p7ihhs8ta7jkgoumvkr3s; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.normes
    ADD CONSTRAINT ukm0k8p7ihhs8ta7jkgoumvkr3s UNIQUE (code);


--
-- TOC entry 5002 (class 2606 OID 16636)
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- TOC entry 5014 (class 2606 OID 16644)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 5008 (class 2606 OID 16582)
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- TOC entry 5016 (class 2606 OID 16598)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4971 (class 1259 OID 16618)
-- Name: idx_action_histo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_action_histo ON public.historique_actions USING btree (action);


--
-- TOC entry 4965 (class 1259 OID 16614)
-- Name: idx_audit; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_audit ON public.evaluations_criteres USING btree (audit_id);


--
-- TOC entry 4950 (class 1259 OID 16604)
-- Name: idx_audit_commentaire; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_audit_commentaire ON public.commentaires USING btree (audit_id);


--
-- TOC entry 4943 (class 1259 OID 16601)
-- Name: idx_audit_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_audit_type ON public.audits USING btree (type);


--
-- TOC entry 4944 (class 1259 OID 16603)
-- Name: idx_auditeur; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_auditeur ON public.audits USING btree (auditeur_id);


--
-- TOC entry 4951 (class 1259 OID 16605)
-- Name: idx_auteur_commentaire; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_auteur_commentaire ON public.commentaires USING btree (auteur_id);


--
-- TOC entry 4955 (class 1259 OID 16608)
-- Name: idx_categorie; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_categorie ON public.criteres USING btree (categorie);


--
-- TOC entry 4956 (class 1259 OID 16607)
-- Name: idx_code_critere; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_code_critere ON public.criteres USING btree (code);


--
-- TOC entry 4975 (class 1259 OID 16621)
-- Name: idx_code_norme; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_code_norme ON public.normes USING btree (code);


--
-- TOC entry 4966 (class 1259 OID 16615)
-- Name: idx_critere; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_critere ON public.evaluations_criteres USING btree (critere_id);


--
-- TOC entry 4957 (class 1259 OID 16609)
-- Name: idx_criticite; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_criticite ON public.criteres USING btree (criticite);


--
-- TOC entry 4972 (class 1259 OID 16620)
-- Name: idx_date_action; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_date_action ON public.historique_actions USING btree (date_action);


--
-- TOC entry 4945 (class 1259 OID 16599)
-- Name: idx_date_audit; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_date_audit ON public.audits USING btree (date_audit);


--
-- TOC entry 4952 (class 1259 OID 16606)
-- Name: idx_date_creation_commentaire; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_date_creation_commentaire ON public.commentaires USING btree (date_creation);


--
-- TOC entry 4981 (class 1259 OID 16628)
-- Name: idx_date_creation_notif; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_date_creation_notif ON public.notifications USING btree (date_creation);


--
-- TOC entry 4982 (class 1259 OID 16625)
-- Name: idx_destinataire; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_destinataire ON public.notifications USING btree (destinataire_id);


--
-- TOC entry 5009 (class 1259 OID 16639)
-- Name: idx_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_email ON public.users USING btree (email);


--
-- TOC entry 4973 (class 1259 OID 16619)
-- Name: idx_entite_histo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_entite_histo ON public.historique_actions USING btree (entite);


--
-- TOC entry 4946 (class 1259 OID 16602)
-- Name: idx_etablissement; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_etablissement ON public.audits USING btree (etablissement_id);


--
-- TOC entry 4995 (class 1259 OID 16633)
-- Name: idx_evaluation_preuve; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_evaluation_preuve ON public.preuves USING btree (evaluation_id);


--
-- TOC entry 4983 (class 1259 OID 16626)
-- Name: idx_lu; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_lu ON public.notifications USING btree (lu);


--
-- TOC entry 4960 (class 1259 OID 16610)
-- Name: idx_nom; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_nom ON public.etablissements USING btree (nom);


--
-- TOC entry 4976 (class 1259 OID 16622)
-- Name: idx_pays; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pays ON public.normes USING btree (pays);


--
-- TOC entry 4947 (class 1259 OID 16600)
-- Name: idx_statut; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_statut ON public.audits USING btree (statut);


--
-- TOC entry 4967 (class 1259 OID 16613)
-- Name: idx_statut_conformite; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_statut_conformite ON public.evaluations_criteres USING btree (statut);


--
-- TOC entry 4987 (class 1259 OID 16629)
-- Name: idx_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_token ON public.password_reset_tokens USING btree (token);


--
-- TOC entry 4961 (class 1259 OID 16611)
-- Name: idx_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_type ON public.etablissements USING btree (type);


--
-- TOC entry 4996 (class 1259 OID 16634)
-- Name: idx_type_fichier; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_type_fichier ON public.preuves USING btree (type_fichier);


--
-- TOC entry 4984 (class 1259 OID 16627)
-- Name: idx_type_notif; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_type_notif ON public.notifications USING btree (type);


--
-- TOC entry 4968 (class 1259 OID 16616)
-- Name: idx_urgence; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_urgence ON public.evaluations_criteres USING btree (urgence);


--
-- TOC entry 4988 (class 1259 OID 16630)
-- Name: idx_user_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_token ON public.password_reset_tokens USING btree (user_id);


--
-- TOC entry 5010 (class 1259 OID 16640)
-- Name: idx_username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_username ON public.users USING btree (username);


--
-- TOC entry 4974 (class 1259 OID 16617)
-- Name: idx_utilisateur_histo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_utilisateur_histo ON public.historique_actions USING btree (utilisateur_id);


--
-- TOC entry 4962 (class 1259 OID 16612)
-- Name: idx_ville; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ville ON public.etablissements USING btree (ville);


--
-- TOC entry 5034 (class 2606 OID 16730)
-- Name: preuves fk1aq99875r1hk91t8cfhwkmhk0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preuves
    ADD CONSTRAINT fk1aq99875r1hk91t8cfhwkmhk0 FOREIGN KEY (evaluation_id) REFERENCES public.evaluations_criteres(id);


--
-- TOC entry 5024 (class 2606 OID 16685)
-- Name: criteres fk1ucm7tdavt89u0qp7y0h6sd3x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.criteres
    ADD CONSTRAINT fk1ucm7tdavt89u0qp7y0h6sd3x FOREIGN KEY (section_id) REFERENCES public.sections(id);


--
-- TOC entry 5027 (class 2606 OID 16700)
-- Name: evaluations_criteres fk385182t9yp3lmjl0fevuge1c8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluations_criteres
    ADD CONSTRAINT fk385182t9yp3lmjl0fevuge1c8 FOREIGN KEY (critere_id) REFERENCES public.criteres(id);


--
-- TOC entry 5030 (class 2606 OID 16710)
-- Name: norme_types_etablissements fk38n49snpovurh1j7uj0dcv6ji; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.norme_types_etablissements
    ADD CONSTRAINT fk38n49snpovurh1j7uj0dcv6ji FOREIGN KEY (norme_id) REFERENCES public.normes(id);


--
-- TOC entry 5026 (class 2606 OID 16690)
-- Name: etablissements fk6vet5qfpvwe9rhow3t7jgtr2p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etablissements
    ADD CONSTRAINT fk6vet5qfpvwe9rhow3t7jgtr2p FOREIGN KEY (norme_id) REFERENCES public.normes(id);


--
-- TOC entry 5017 (class 2606 OID 16645)
-- Name: audits fk7k50rfv9e5nx76br7k99jug0s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT fk7k50rfv9e5nx76br7k99jug0s FOREIGN KEY (audit_initial_id) REFERENCES public.audits(id);


--
-- TOC entry 5018 (class 2606 OID 16655)
-- Name: audits fk9fxw0cpl6n1d4eshhor2spp6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT fk9fxw0cpl6n1d4eshhor2spp6 FOREIGN KEY (etablissement_id) REFERENCES public.etablissements(id);


--
-- TOC entry 5021 (class 2606 OID 16670)
-- Name: commentaires fk9ln3ltemfs8wge22nx61vns9t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commentaires
    ADD CONSTRAINT fk9ln3ltemfs8wge22nx61vns9t FOREIGN KEY (auteur_id) REFERENCES public.users(id);


--
-- TOC entry 5022 (class 2606 OID 16665)
-- Name: commentaires fkbywnhom7dmlyx3w61xahswf50; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commentaires
    ADD CONSTRAINT fkbywnhom7dmlyx3w61xahswf50 FOREIGN KEY (audit_id) REFERENCES public.audits(id);


--
-- TOC entry 5019 (class 2606 OID 16660)
-- Name: audits fkdbia1tv76psstcbrfjy7i1wko; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT fkdbia1tv76psstcbrfjy7i1wko FOREIGN KEY (validateur_id) REFERENCES public.users(id);


--
-- TOC entry 5025 (class 2606 OID 16680)
-- Name: criteres fkg8gyj2bl54kfglx77e964c6bd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.criteres
    ADD CONSTRAINT fkg8gyj2bl54kfglx77e964c6bd FOREIGN KEY (norme_id) REFERENCES public.normes(id);


--
-- TOC entry 5035 (class 2606 OID 16735)
-- Name: sections fkghe22dif87flv71rowr1yx1xl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT fkghe22dif87flv71rowr1yx1xl FOREIGN KEY (norme_id) REFERENCES public.normes(id);


--
-- TOC entry 5028 (class 2606 OID 16695)
-- Name: evaluations_criteres fkgvp9frnb5tt3m33qpiiaxugkv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluations_criteres
    ADD CONSTRAINT fkgvp9frnb5tt3m33qpiiaxugkv FOREIGN KEY (audit_id) REFERENCES public.audits(id);


--
-- TOC entry 5036 (class 2606 OID 16740)
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 5037 (class 2606 OID 16745)
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 5032 (class 2606 OID 16720)
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 5020 (class 2606 OID 16650)
-- Name: audits fkkghrxoccgjf1w0ut2uwnm0pal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT fkkghrxoccgjf1w0ut2uwnm0pal FOREIGN KEY (auditeur_id) REFERENCES public.users(id);


--
-- TOC entry 5029 (class 2606 OID 16705)
-- Name: historique_actions fkqeia3bjgkuia9jic4wuj3eqpv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historique_actions
    ADD CONSTRAINT fkqeia3bjgkuia9jic4wuj3eqpv FOREIGN KEY (utilisateur_id) REFERENCES public.users(id);


--
-- TOC entry 5031 (class 2606 OID 16715)
-- Name: notifications fkqfqbwour5dn6mgbd3a1t5tymx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkqfqbwour5dn6mgbd3a1t5tymx FOREIGN KEY (destinataire_id) REFERENCES public.users(id);


--
-- TOC entry 5033 (class 2606 OID 16725)
-- Name: photos_etablissement fksclpvdhb2cof40uusf4if83mb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photos_etablissement
    ADD CONSTRAINT fksclpvdhb2cof40uusf4if83mb FOREIGN KEY (etablissement_id) REFERENCES public.etablissements(id);


--
-- TOC entry 5023 (class 2606 OID 16675)
-- Name: commentaires fkt44x95shwcs7l20njl33wvu5e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commentaires
    ADD CONSTRAINT fkt44x95shwcs7l20njl33wvu5e FOREIGN KEY (parent_id) REFERENCES public.commentaires(id);


-- Completed on 2026-01-09 21:39:23

--
-- PostgreSQL database dump complete
--

\unrestrict 3XhUOB0vpqz1VuaAbypSrwfMuymbNe2d8fUJypD2ikVTQAgFtSkGNLUnggQiPKY

